name: PR
permissions:
  contents: read
on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "*/data-grid/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Copy to .env
        run: |
          state=$(cat state.yaml)
          printf "PUBLIC_STATE=\"\n$state\"" > .env
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install-deps
      - run: pnpm exec playwright install
      - run: pnpm run build
      - run: pnpm test
